const ActionTypes = {
    CLEAR_MESSAGE:'CLEAR_MESSAGE',
    ADMIN_LOGIN_REQUEST:'ADMIN_LOGIN_REQUEST',
    USER_LOGIN_REQUEST:'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL:'USER_LOGIN_FAIL'
  };
  
  export default ActionTypes;
  